# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6e048d46bbd4d29c6c1c41a48d4fb2cb3863e78f21efffddc422be1d88203f89647c1e11ab1626270414760bd31056ce9edbae172bb09ad49324efd5b5bb587

test:
  secret_key_base: 50915c09760e23cc57d1ecf2d45c06ca55b1809b8428605a28ed0ed0f52ad3e1c38f56118542dd81b11ad8776bbda63fbe8f661e2ef45dbb25e9c5f8057a520e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
